apiVersion: v1
kind: Service
metadata:
  name: react-landmarck-service
spec:
  selector:
    app: react-landmarck
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
